'use client'

import "./globals.css";
import { MantineProvider, ButtonStylesParams } from "@mantine/core";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import { AppProps } from "next/app";
const manropeFont = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "takeIt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        theme={{
          /** Mantine theme override here */
          colorScheme: "light",
          colors: {
            primary: [
              "#ECF0F4",
              "#AFC7DE",
              "#8EB6DB",
              "#6AA6DE",
              "#4098EA",
              "#108CFF",
              "#187EDC",
              "#2870B4",
              "#306595",
              "#345A7D",
            ],
            secondary: [
              "#3C4755",
              "#2C3B4C",
              "#253548",
              "#1D3046",
              "#162B44",
              "#182739",
              "#192330",
              "#182029",
              "#171D24",
              "#161A1F",
            ],
            black: [
              "#000000",
              "#111111",
              "#222222",
              "#333333",
              "#444444",
              "#555555",
              "#666666",
              "#777777",
              "#888888",
              "#999999",
            ],
          },
          components: {
            Button: {
              styles: (theme, params: ButtonStylesParams, { variant }) => ({
                label: {
                  fontWeight: 500,
                },
              }),
            },
          },
          primaryShade: 5,
          primaryColor: "primary",
          fontFamily: manropeFont.style.fontFamily,
          defaultRadius: "var(--general-box-border-radius)",
          headings: {
            fontFamily: manropeFont.style.fontFamily,
            sizes: {
              h1: { fontSize: "var(--h1)" },
              h2: { fontSize: "var(--h2)" },
              h3: { fontSize: "var(--h3)" },
              h4: { fontSize: "var(--h4)" },
              h5: { fontSize: "var(--h5)" },
              h6: { fontSize: "var(--h6)" },
            },
          },
          fontSizes: {
            xs: "0.625rem",
            sm: "0.875rem",
            md: "1rem",
            lg: "1.125rem",
            xl: "1.25rem",
            xxl: "1.5rem",
          },
        }}
      >
        {/* <RouterTransition /> */}
        <body className={manropeFont.className}>{children}</body>
      </MantineProvider>
    </html>
  );
}
